title: Direito Ã  Sombra

baseurl: ''
permalink: :title/

include: ['_pages']

exclude: [
  .git,
  .gitignore,
  Gemfile,
  Gemfile.lock,
  README.md,
  .sass-cache/,
  .jekyll-cache/,
  gemfiles/,
  node_modules/
]

markdown: kramdown
future: false
port: 8181

# Defaults
defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page
